default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: rails_editor_development

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: wonderful_editor_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: rails_editor_production
  password: <%= ENV['RAILS_EDITOR_DATABASE_PASSWORD'] %>
